config/urls.py
from django.contrib import admin
from django.urls import path, include 
 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),  
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

core/urls.py
from django.urls import path
from .views import HomePageView, PostCreateView , AboutPageView,PostListView, PostDetailView,PostUpdateView,UserActionUpdateView,UserActionComment


urlpatterns = [
    path('', HomePageView.as_view(), name='home'),  
    path('posts/', PostListView.as_view(), name='posts'),
    path('posts/<int:pk>/', PostDetailView.as_view(), name='post_detail'),
    path('posts/create/', PostCreateView.as_view() , name='create_post'),
    path('about/',  AboutPageView.as_view(), name='about'),
    path('posts/<int:pk>/edit/', PostUpdateView.as_view(), name='post_edit'),
    path('posts/<int:pk>/user_action_update/', UserActionUpdateView.as_view(), name='user_action_update'),
    path('posts/<int:pk>/user_action_comment/',UserActionComment.as_view(), name='user_action_comment'),
]

core/models.py
from django.db import models
from datetime import datetime
from django.utils import timezone
from django.contrib.auth.models import User



# class Author(models.Model):
#     name = models.CharField(max_length=100,verbose_name="Avtor ati")
#     bio = models.TextField(blank=True, verbose_name="Ozi haqqinda")

#     def __str__(self):
#         return self.name
    


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name="Kategoriya ati")

    def __str__(self):
        return self.name
    

class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name="Teg ati")

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    is_published = models.BooleanField(default=False, verbose_name="Post juklengenba?")
    #view_count = models.IntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Jaratilgan waqti")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Ozgergen waqti")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Kategoriya", related_name='posts')
    tags = models.ManyToManyField(Tag, blank=True, verbose_name="Tegler", related_name='posts')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Avtor", related_name='posts')
    #author = models.ForeignKey(Author, on_delete=models.CASCADE, verbose_name="Avtor", related_name='posts')

    @property
    def get_view_count(self):
        return self.user_actions.aggregate(models.Sum('view_count'))['view_count__sum'] or 0
    
    @property
    def get_like_count(self):
        return self.user_actions.filter(liked=True).count()
    
    @property
    def get_dislike_count(self):
        return self.user_actions.filter(disliked=True).count()




    def __str__(self):
        return self.title
    

class UserPostAction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='actions')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='user_actions')
    view_count = models.IntegerField(default=1)
    liked = models.BooleanField(default=False)
    disliked = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    

    class Meta:
        unique_together = ('user', 'post')

    def __str__(self):
        return f"{self.user.username} - {self.post.title}"

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Comment by: {self.user.username} - {self.post.title}"

templates/about.html
{% extends "base.html" %}

{% block title %}Bas bet  {% endblock %} 

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">About</li>
  </ol>
</nav>

<h1> Biz haqqimizda</h1>
<p> Birdene magliwmatlar </p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} Blog sayt {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css">

</head>

<body>

    <header>


        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Blog sayt</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                    aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/posts/">Postlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/about/">About</a>
                        </li>
                       {% if user.is_authenticated %}
                                <li class="nav-item d-flex align-items-center gap-2 ms-3">
                                    <a class="nav-link" href="{% url 'profile' %}"><i class="bi bi-person-circle"></i> {{ user.username }}</a>
                                </li>
                            {% else %}
                                <li class="nav-item d-flex align-items-center gap-2 ms-3">                                    
                                    <a class="btn btn-primary" href="{% url 'login' %}">Kiriw</a>
                                    <a class="btn btn-success" href="{% url 'signup' %}">Dizimnen ótiw</a>
                                </li>
                            {% endif %} 

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="container mt-4">
        {% block content %}
        {% endblock %}
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI"
        crossorigin="anonymous"></script>
</body>

</html>

templates/create_post.html
{% extends "base.html" %}

{% block title %}Jana post   {% endblock %} 

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>

<h1>Jana post</h1>
<form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Submit</button>
</form>


{% endblock %}

templates/home.html
{% extends "base.html" %}

{% block title %}Bas bet  {% endblock %} 

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Home</li>
  </ol>
</nav>

<h1> Blok sayt</h1>
<p> Bul birinshi ameliyat proekti </p>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}


{% block title %} Detail {% endblock %}


{% block content %} 

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}


<div class="d-flex justify-content-between align-items-center">
  <h1>{{object.title}}</h1>  
  <div>
     {% if perms.core.delete_post %}
    <button  class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Oshiriw</button>
    {% endif %}
     {% if perms.core.change_post %}
    <a href="/posts/{{object.id}}/edit/" class="btn btn-warning btn-sm">Ozgertiw</a>
    {% endif %}
  </div>
</div>
<p>{{object.content}}</p>
 
<p>Author: {{object.user}} </p>
<p>Post jazilgan waqti: {{object.created_at}}</p>

<form action="user_action_update/" method="post" class="d-flex align-items-center gap-3">
  {% csrf_token %}

  <!-- Like button -->
  <button type="submit" name="action" value="like"
          class="btn {% if user_post_action and user_post_action.liked %}btn-success{% else %}btn-outline-success{% endif %} d-flex align-items-center gap-1">
    <i class="bi bi-hand-thumbs-up{% if user_post_action and user_post_action.liked %}-fill{% endif %}"></i>
    Like
  </button>

  <!-- Dislike button -->
  <button type="submit" name="action" value="dislike"
          class="btn {% if user_post_action and user_post_action.disliked %}btn-danger{% else %}btn-outline-danger{% endif %} d-flex align-items-center gap-1">
    <i class="bi bi-hand-thumbs-down{% if user_post_action and user_post_action.disliked %}-fill{% endif %}"></i>
    Dislike
  </button>
</form>

<hr class="my-4">


 {% comment %} Komment qaldiriw bolimi {% endcomment %}
<h2>Comments:</h2>

 <div class="container my-4">
  <div class="card shadow-sm">
    <div class="card-body">
      <h5 class="card-title mb-3">Kommentariya qaldiriw</h5>

      <form method="post" action="{% url 'user_action_comment' object.id %}" name="text">
          {% csrf_token %}
        <div class="mb-3">
          <textarea name="comment_text" id="id_body" rows="4"class="form-control"placeholder="Kommentariyanizdi jazip qaldirin..." required ></textarea>
        </div>

        <div class="text-end">
          <button type="submit" class="btn btn-primary px-4">Jiberiw</button>
        </div>
      </form>
    </div>
  </div>
</div>


{% comment %} Kommentariya bolimi {% endcomment %}

{% for comment in object.comments.all %} 

<div class="card">
  <div class="d-flex justify-content-between align-items-center">
    <div class="card-header ">
      {{comment.user}} 
    </div>
    <div>
      {% if user == comment.user or user.is_superuser and perms.core.delete_comment %}
    <button  class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModalComment{{comment.id}}">Oshiriw</button>
    {% endif %}
    </div>
  </div>
  <div class="card-body">
    <figure>
      <blockquote class="blockquote">
        <p>{{comment.text}}</p>
      </blockquote>
      <figcaption class="blockquote-footer">
       <small>  <cite title="Source Title">{{comment.created_date|date:"d.m.Y H:i" }}</cite> </small> 
      </figcaption>
    </figure>
  </div>
 <hr class="my-1">
</div>

{% comment %} Modal Komment {% endcomment %}
<div class="modal fade" id="deleteModalComment{{comment.id}}" tabindex="-1" aria-labelledby="deleteCommentModalLabel{{comment.id}}" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteCommentModalLabel{{comment.id}}">Kommentariyani oshirejaqsizba?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Yopish"></button>
      </div>
      {{comment.text}}
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yaq</button>
        <form method="post" action="{% url 'user_action_comment' object.id %}">
          {% csrf_token %}
          <input type="hidden" name="delete_comment_id" value="{{ comment.id }}">
          <button type="submit" class="btn btn-danger">Oshiriw</button>
         
        </form>
      </div>
    </div>
  </div>
</div>

 {%endfor%}


 {% comment %} Popular posts {% endcomment %}
<h2>Popular posts:</h2>

<div class="row g-4 mt-3">
    {% for post in popular_posts %}
    <div class="col-4">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{post.title}}</h5>
                <p class="card-text">{{post.content|truncatewords:5}}</p>
                <a href="/posts/{{post.id}}/" class="btn btn-primary">Toliq oqiw</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


<div class="modal" tabindex="-1" id="deleteModal" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">"{{ object.title }}" atli postti rastanda oshirejaqsizba?</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
     
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Yaq</button>
        <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-primary">Awa,oshiriw</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

templates/post_edit.html
{% extends "base.html" %}

{% block title %}Postti ozgertiw{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Home</li>
    </ol>
</nav>

<div class="card p-2 mx-auto" style="width: 48rem;">
    <h1 class="text-center card-title">Postti ozgertiw</h1>
    <div class="card-body">
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Saqlaw</button>
        </form>
    </div>
</div>
{% endblock %}

templates/posts.html
{% extends "base.html" %}

{% block title %}Postlar dizimi{% endblock %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Postlar</li>
  </ol>
</nav>

<div class="d-flex justify-content-between align-items-center">
  <h1>Postlar dizimi</h1>
  {% if perms.core.add_post %}
  <a href="/posts/create/" class="btn btn-success">+ Jana post</a>
  {% endif %}
</div>


<form method="GET" class="row g-3 mt-3">
  <div class="col-md-4">
    <input type="text" name="search" class="form-control" placeholder="Izlew..." value="{{ request.GET.search }}">
  </div>
  <div class="col-md-3">
    <select name="category" class="form-select">
      <option value="">Barliq kategoriya</option>
      {% for category in categories %}
      <option value="{{ category.id }}" {% if request.GET.category == category.id|stringformat:"s" %}selected{% endif %}>{{ category.name }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="col-md-3">
    <select name="author" class="form-select">
      <option value="">Barliq avtorlar</option>
      {% for author in authors %}
      <option value="{{ author.id }}" {% if request.GET.author == author.id|stringformat:"s" %}selected{% endif %}>{{ author.username }}</option>
      {% endfor %}
    </select>
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i> Filtrlaw</button>
  </div>
</form>




<div class="row g-4 mt-3">
  {% for post in object_list %}
  <div class="col-4">
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{post.title}}</h5>
        <div class="d-flex gap-3 mb-2">
          <small class="badge text-bg-secondary">{{post.category.name}}</small>
          <small class="text-muted"><i class="bi bi-person"></i> {{post.author.username}} </small>
          <small class="text-muted"><i class="bi bi-calendar-week"></i> {{post.created_at|date:"Y-m-d H:i"}}</small>
        </div>
        <p class="card-text">{{post.content|truncatewords:5}}</p>
        <p>
          {% for tag in post.tags.all %}
          <small class="text-muted">#{{tag.name}}</small>
          {% endfor %}
        </p>

        <div class="d-flex justify-content-between align-items-center ">
          <a href="/posts/{{post.id}}/" class="btn btn-primary">Tolıq oqıw</a>

            {% comment %} <i class="bi bi-hand-thumbs-up"></i> {{post.get_like_count}}
            <i class="bi bi-hand-thumbs-down"></i> {{post.get_dislike_count}}
          <span class="text-muted"><i class="bi bi-eye"></i> {{ post.get_view_count}}</span> {% endcomment %}
            
  <div class="d-flex align-items-center gap-3">

    
    <div class="d-flex align-items-center text-success fs-5">
      <i class="bi bi-hand-thumbs-up me-1"></i>
      <span class="fw-semibold">{{ post.get_like_count }}</span>
    </div>

   
    <div class="d-flex align-items-center text-danger fs-5">
      <i class="bi bi-hand-thumbs-down me-1"></i>
      <span class="fw-semibold">{{ post.get_dislike_count }}</span>
    </div>

   
    <div class="d-flex align-items-center text-secondary fs-6">
      <i class="bi bi-eye me-1"></i>
      <span>{{ post.get_view_count }}</span>
    </div>

  </div>
        </div>
        
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}